name: Server Sideloads

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        clean: false
    
    - name: Update config.json
      run: echo "`jq '.version="${{ github.run_number }}"' manifests/server/integration/manifest.json`" > manifests/server/integration/manifest.json
    
    - name: Create zip file    
      uses: papeloto/action-zip@v1
      with:
        files: /manifests/server/integration/
        dest: Jira.Server.Sideload.${{ github.run_number }}-Integration.zip
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: myartifact
        path: ${{ github.workspace }}/Jira.Server.Sideload.${{ github.run_number }}-Integration.zip
        
    - name: Update config.json
      run: echo "`jq '.version="${{ github.run_number }}"' manifests/server/staging/manifest.json`" > manifests/server/staging/manifest.json
    
    - name: Create zip file    
      run: |
        ls
        
    - name: Create zip file    
      run: |
        zip -r Jira.Server.Sideload.${{ github.run_number }}-Staging.zip /manifests/server/staging/
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: myartifact
        path: ${{ github.workspace }}/Jira.Server.Sideload.${{ github.run_number }}-Staging.zip
        
    - name: Update config.json
      run: echo "`jq '.version="${{ github.run_number }}"' manifests/server/production/manifest.json`" > manifests/server/production/manifest.json
    
    - name: Create zip file    
      uses: papeloto/action-zip@v1
      with:
        files: /manifests/server/production/
        dest: Jira.Server.Sideload.${{ github.run_number }}-Production.zip
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: myartifact
        path: ${{ github.workspace }}/Jira.Server.Sideload.${{ github.run_number }}-Production.zip

